-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.mst_kabupaten
(
    kd_prov character varying(4) COLLATE pg_catalog."default",
    kd_kab character varying(6) COLLATE pg_catalog."default" NOT NULL,
    description character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT mst_kabupaten_pkey PRIMARY KEY (kd_kab)
);

CREATE TABLE IF NOT EXISTS public.mst_provinsi
(
    kd_prov character varying(4) COLLATE pg_catalog."default" NOT NULL,
    nama_prov character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT mst_provinsi_pkey PRIMARY KEY (kd_prov)
);

CREATE TABLE IF NOT EXISTS public.nasabah
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nik character varying(20) COLLATE pg_catalog."default",
    nama character varying(50) COLLATE pg_catalog."default",
    alamat character varying(300) COLLATE pg_catalog."default",
    no_hp character varying(20) COLLATE pg_catalog."default",
    kd_prov character varying(4) COLLATE pg_catalog."default",
    kd_kab character varying(6) COLLATE pg_catalog."default",
    foto_profile character varying(250) COLLATE pg_catalog."default",
    foto_ktp character varying(250) COLLATE pg_catalog."default",
    hobi character varying(20) COLLATE pg_catalog."default",
    gaji money,
    CONSTRAINT nasabah_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default",
    icon character varying COLLATE pg_catalog."default",
    base64 character varying COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.nasabah
    ADD CONSTRAINT nasabah_kd_kab_fkey FOREIGN KEY (kd_kab)
    REFERENCES public.mst_kabupaten (kd_kab) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.nasabah
    ADD CONSTRAINT nasabah_kd_prov_fkey FOREIGN KEY (kd_prov)
    REFERENCES public.mst_provinsi (kd_prov) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;